import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Pages are statically generated by default (SSG) for best Core Web Vitals.
  // Vercel serves them as static HTML; no server needed for content pages.
};

export default nextConfig;
