import type { ClassDef, ChapterStub } from "@/lib/types";

/** Stable slug from a human title (matches authored chapter slugs). */
export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Build a chapter roadmap from [order, title] pairs. */
function chapters(list: [number, string][]): ChapterStub[] {
  return list.map(([order, title]) => ({ order, title, slug: slugify(title) }));
}

const ICON = {
  maths: "➗",
  science: "⚛️",
  social: "🏛️",
  english: "✏️",
} as const;

const COLOR = {
  maths: "#ff5d73",
  science: "#3257f0",
  social: "#b56a16",
  english: "#1faf6b",
} as const;

const CBSE_DEFS: Omit<ClassDef, "board">[] = [
  {
    id: "1",
    roman: "I",
    label: "Class 1",
    blurb: "Class 1 CBSE — new NCERT Mridang (English). More subjects coming soon.",
    subjects: [
      {
        key: "english",
        name: "English",
        icon: ICON.english,
        color: COLOR.english,
        chapters: chapters([
          [1, "Two Little Hands"],
          [2, "Greetings"],
          [3, "Picture Time"],
          [4, "The Cap-seller and the Monkeys"],
          [5, "A Farm"],
          [6, "Fun with Pictures"],
          [7, "The Food We Eat"],
          [8, "The Four Seasons"],
          [9, "Anandi's Rainbow"],
        ]),
      },
    ],
  },
  {
    id: "6",
    roman: "VI",
    label: "Class 6",
    blurb: "Class 6 CBSE — new NCERT Ganita Prakash (Maths) & Curiosity (Science).",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "Patterns in Mathematics"],
          [2, "Lines and Angles"],
          [3, "Number Play"],
          [4, "Data Handling and Presentation"],
          [5, "Prime Time"],
          [6, "Perimeter and Area"],
          [7, "Fractions"],
          [8, "Playing with Constructions"],
          [9, "Symmetry"],
          [10, "The Other Side of Zero"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "The Wonderful World of Science"],
          [2, "Diversity in the Living World"],
          [3, "Mindful Eating A Path to a Healthy Body"],
          [4, "Exploring Magnets"],
          [5, "Measurement of Length and Motion"],
          [6, "Materials Around Us"],
          [7, "Temperature and its Measurement"],
          [8, "A Journey through States of Water"],
          [9, "Methods of Separation in Everyday Life"],
          [10, "Living Creatures Exploring their Characteristics"],
          [11, "Natures Treasures"],
          [12, "Beyond Earth"],
        ]),
      },
    ],
  },
  {
    id: "7",
    roman: "VII",
    label: "Class 7",
    blurb: "Class 7 CBSE — new NCERT Ganita Prakash (Maths) & Curiosity (Science).",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "Large Numbers Around Us"],
          [2, "Arithmetic Expressions"],
          [3, "A Peek Beyond the Point"],
          [4, "Expressions using Letter-Numbers"],
          [5, "Parallel and Intersecting Lines"],
          [6, "Number Play"],
          [7, "A Tale of Three Intersecting Lines"],
          [8, "Working with Fractions"],
          [9, "Geometric Twins"],
          [10, "Operations with Integers"],
          [11, "Finding Common Ground"],
          [12, "Another Peek Beyond the Point"],
          [13, "Connecting the Dots"],
          [14, "Constructions and Tilings"],
          [15, "Finding the Unknown"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "The Ever-Evolving World of Science"],
          [2, "Exploring Substances Acidic Basic and Neutral"],
          [3, "Electricity Circuits and their Components"],
          [4, "The World of Metals and Non-metals"],
          [5, "Changes Around Us Physical and Chemical"],
          [6, "Adolescence A Stage of Growth and Change"],
          [7, "Heat Transfer in Nature"],
          [8, "Measurement of Time and Motion"],
          [9, "Life Processes in Animals"],
          [10, "Life Processes in Plants"],
          [11, "Light Shadows and Reflections"],
          [12, "Earth Moon and the Sun"],
        ]),
      },
    ],
  },
  {
    id: "8",
    roman: "VIII",
    label: "Class 8",
    blurb: "Class 8 CBSE — new NCERT Ganita Prakash (Maths) & Curiosity (Science).",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "A Square and A Cube"],
          [2, "Power Play"],
          [3, "A Story of Numbers"],
          [4, "Quadrilaterals"],
          [5, "Number Play"],
          [6, "We Distribute Yet Things Multiply"],
          [7, "Proportional Reasoning 1"],
          [8, "Fractions in Disguise"],
          [9, "The Baudhayana Pythagoras Theorem"],
          [10, "Proportional Reasoning 2"],
          [11, "Exploring Some Geometric Themes"],
          [12, "Tales by Dots and Lines"],
          [13, "Algebra Play"],
          [14, "Area"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "Exploring the Investigative World of Science"],
          [2, "The Invisible Living World Beyond Our Naked Eye"],
          [3, "Health The Ultimate Treasure"],
          [4, "Electricity Magnetic and Heating Effects"],
          [5, "Exploring Forces"],
          [6, "Pressure Winds Storms and Cyclones"],
          [7, "Particulate Nature of Matter"],
          [8, "Nature of Matter Elements Compounds and Mixtures"],
          [9, "The Amazing World of Solutes Solvents and Solutions"],
          [10, "Light Mirrors and Lenses"],
          [11, "Keeping Time with the Skies"],
          [12, "How Nature Works in Harmony"],
          [13, "Our Home Earth A Unique Life Sustaining Planet"],
        ]),
      },
    ],
  },
  {
    id: "9",
    roman: "IX",
    label: "Class 9",
    blurb: "Class 9 CBSE — Maths, Science, Social Science and English.",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "Number Systems"],
          [2, "Polynomials"],
          [3, "Coordinate Geometry"],
          [4, "Linear Equations in Two Variables"],
          [5, "Introduction to Euclids Geometry"],
          [6, "Lines and Angles"],
          [7, "Triangles"],
          [8, "Quadrilaterals"],
          [9, "Circles"],
          [10, "Herons Formula"],
          [11, "Surface Areas and Volumes"],
          [12, "Statistics"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "Matter in Our Surroundings"],
          [2, "Is Matter Around Us Pure"],
          [3, "Atoms and Molecules"],
          [4, "Structure of the Atom"],
          [5, "The Fundamental Unit of Life"],
          [6, "Tissues"],
          [7, "Motion"],
          [8, "Force and Laws of Motion"],
          [9, "Gravitation"],
          [10, "Work and Energy"],
          [11, "Sound"],
          [12, "Improvement in Food Resources"],
        ]),
      },
      {
        key: "social-science",
        name: "Social Science",
        icon: ICON.social,
        color: COLOR.social,
        chapters: chapters([
          [1, "The French Revolution"],
          [2, "Socialism in Europe and the Russian Revolution"],
          [3, "Nazism and the Rise of Hitler"],
          [4, "Forest Society and Colonialism"],
          [5, "Pastoralists in the Modern World"],
          [6, "India Size and Location"],
          [7, "Physical Features of India"],
          [8, "Drainage"],
          [9, "Climate"],
          [10, "Natural Vegetation and Wildlife"],
          [11, "Population"],
          [12, "What is Democracy Why Democracy"],
          [13, "Constitutional Design"],
          [14, "Electoral Politics"],
          [15, "Working of Institutions"],
          [16, "Democratic Rights"],
          [17, "The Story of Village Palampur"],
          [18, "People as Resource"],
          [19, "Poverty as a Challenge"],
          [20, "Food Security in India"],
        ]),
      },
      {
        key: "english",
        name: "English",
        icon: ICON.english,
        color: COLOR.english,
        chapters: chapters([
          [1, "The Fun They Had"],
          [2, "The Sound of Music"],
          [3, "The Little Girl"],
          [4, "A Truly Beautiful Mind"],
          [5, "The Snake and the Mirror"],
          [6, "My Childhood"],
          [7, "Reach for the Top"],
          [8, "Kathmandu"],
          [9, "If I Were You"],
          [10, "The Road Not Taken"],
          [11, "Wind"],
          [12, "Rain on the Roof"],
          [13, "The Lake Isle of Innisfree"],
          [14, "A Legend of the Northland"],
          [15, "No Men Are Foreign"],
          [16, "On Killing a Tree"],
          [17, "A Slumber Did My Spirit Seal"],
          [18, "The Lost Child"],
          [19, "The Adventures of Toto"],
          [20, "Iswaran the Storyteller"],
          [21, "In the Kingdom of Fools"],
          [22, "The Happy Prince"],
          [23, "Weathering the Storm in Ersama"],
          [24, "The Last Leaf"],
          [25, "A House Is Not a Home"],
          [26, "The Beggar"],
          [27, "Grammar and Writing Skills"],
        ]),
      },
    ],
  },
  {
    id: "10",
    roman: "X",
    label: "Class 10",
    blurb:
      "Class 10 CBSE board prep — chapter notes, formulas, MCQ quizzes and important questions.",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "Real Numbers"],
          [2, "Polynomials"],
          [3, "Pair of Linear Equations in Two Variables"],
          [4, "Quadratic Equations"],
          [5, "Arithmetic Progressions"],
          [6, "Triangles"],
          [7, "Coordinate Geometry"],
          [8, "Introduction to Trigonometry"],
          [9, "Some Applications of Trigonometry"],
          [10, "Circles"],
          [11, "Areas Related to Circles"],
          [12, "Surface Areas and Volumes"],
          [13, "Statistics"],
          [14, "Probability"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "Chemical Reactions and Equations"],
          [2, "Acids Bases and Salts"],
          [3, "Metals and Non-metals"],
          [4, "Carbon and its Compounds"],
          [5, "Life Processes"],
          [6, "Control and Coordination"],
          [7, "How do Organisms Reproduce"],
          [8, "Heredity"],
          [9, "Light Reflection and Refraction"],
          [10, "The Human Eye and the Colourful World"],
          [11, "Electricity"],
          [12, "Magnetic Effects of Electric Current"],
          [13, "Our Environment"],
        ]),
      },
      {
        key: "social-science",
        name: "Social Science",
        icon: ICON.social,
        color: COLOR.social,
        chapters: chapters([
          [1, "The Rise of Nationalism in Europe"],
          [2, "Nationalism in India"],
          [3, "The Making of a Global World"],
          [4, "The Age of Industrialisation"],
          [5, "Print Culture and the Modern World"],
          [6, "Resources and Development"],
          [7, "Forest and Wildlife Resources"],
          [8, "Water Resources"],
          [9, "Agriculture"],
          [10, "Minerals and Energy Resources"],
          [11, "Manufacturing Industries"],
          [12, "Lifelines of National Economy"],
          [13, "Power Sharing"],
          [14, "Federalism"],
          [15, "Gender Religion and Caste"],
          [16, "Political Parties"],
          [17, "Outcomes of Democracy"],
          [18, "Development"],
          [19, "Sectors of the Indian Economy"],
          [20, "Money and Credit"],
          [21, "Globalisation and the Indian Economy"],
          [22, "Consumer Rights"],
        ]),
      },
      {
        key: "english",
        name: "English",
        icon: ICON.english,
        color: COLOR.english,
        chapters: chapters([
          [1, "A Letter to God"],
          [2, "Nelson Mandela A Long Walk to Freedom"],
          [3, "Two Stories about Flying"],
          [4, "From the Diary of Anne Frank"],
          [5, "Glimpses of India"],
          [6, "Mijbil the Otter"],
          [7, "Madam Rides the Bus"],
          [8, "The Sermon at Benares"],
          [9, "The Proposal"],
          [10, "Dust of Snow"],
          [11, "Fire and Ice"],
          [12, "A Tiger in the Zoo"],
          [13, "How to Tell Wild Animals"],
          [14, "The Ball Poem"],
          [15, "Amanda"],
          [16, "The Trees"],
          [17, "Fog"],
          [18, "The Tale of Custard the Dragon"],
          [19, "For Anne Gregory"],
          [20, "A Triumph of Surgery"],
          [21, "The Thiefs Story"],
          [22, "The Midnight Visitor"],
          [23, "A Question of Trust"],
          [24, "Footprints without Feet"],
          [25, "The Making of a Scientist"],
          [26, "The Necklace"],
          [27, "Bholi"],
          [28, "The Book That Saved the Earth"],
          [29, "Grammar and Writing Skills"],
        ]),
      },
    ],
  },
];

/** CBSE classes, tagged with their board. */
export const CBSE_CLASSES: ClassDef[] = CBSE_DEFS.map((c) => ({ ...c, board: "cbse" }));

/**
 * WBBPE (West Bengal Board of Primary Education) — Bengali medium.
 * Skeleton only: subjects are defined but chapters are authored later,
 * once the WB textbooks are available.
 */
export const WBBPE_CLASSES: ClassDef[] = [
  {
    board: "wbbpe",
    id: "1",
    roman: "I",
    label: "Class 1",
    blurb:
      "WBBPE Class 1 — Bengali medium (বাংলা মাধ্যম), from the integrated book ‘আমার বই’ (Amar Boi): Bangla, English & Ganit.",
    subjects: [
      {
        key: "bengali",
        name: "বাংলা",
        icon: "📖",
        color: "#7b54d3",
        chapters: [
          { order: 1, title: "স্বরবর্ণ চেনা", slug: "vowels" },
          { order: 2, title: "ব্যঞ্জনবর্ণ চেনা", slug: "consonants" },
          { order: 3, title: "কার-চিহ্ন", slug: "vowel-signs" },
          { order: 4, title: "বর্ণ জুড়ে শব্দ", slug: "forming-words" },
          { order: 5, title: "ছবি দেখে শব্দ চেনা", slug: "picture-words" },
          { order: 6, title: "ছড়া পড়ি", slug: "rhymes" },
          { order: 7, title: "ছোটো গল্প পড়ি", slug: "story-reading" },
          { order: 8, title: "যুক্তবর্ণ পরিচয়", slug: "conjunct-letters" },
        ],
      },
      {
        key: "english",
        name: "ইংরেজি",
        icon: "✏️",
        color: "#1faf6b",
        chapters: [
          { order: 1, title: "The English Alphabet", slug: "the-alphabet" },
          { order: 2, title: "Capital and Small Letters", slug: "capital-and-small-letters" },
          { order: 3, title: "Beginning Sounds", slug: "beginning-sounds" },
          { order: 4, title: "Words Around Us", slug: "words-around-us" },
          { order: 5, title: "Naming Animals", slug: "naming-animals" },
          { order: 6, title: "Simple Sentences", slug: "simple-sentences" },
          { order: 7, title: "Days of the Week", slug: "days-of-the-week" },
          { order: 8, title: "Reading Aloud", slug: "reading-aloud" },
        ],
      },
      {
        key: "maths",
        name: "গণিত",
        icon: "➗",
        color: "#ff5d73",
        chapters: [
          { order: 1, title: "সংখ্যা চেনা (১–৯)", slug: "numbers-1-to-9" },
          { order: 2, title: "শূন্য (০)", slug: "zero" },
          { order: 3, title: "গোনা ও মেলানো", slug: "counting-and-matching" },
          { order: 4, title: "ছোটো-বড়ো, কম-বেশি", slug: "compare-big-small" },
          { order: 5, title: "ক্রম: আগে ও পরে", slug: "order-before-after" },
          { order: 6, title: "সংখ্যা: ১০ থেকে ২০", slug: "numbers-10-to-20" },
          { order: 7, title: "দশক ও একক", slug: "tens-and-units" },
          { order: 8, title: "যোগ", slug: "addition" },
          { order: 9, title: "বিয়োগ", slug: "subtraction" },
          { order: 10, title: "আকার ও আকৃতি", slug: "shapes" },
          { order: 11, title: "প্যাটার্ন", slug: "patterns" },
        ],
      },
    ],
  },
  {
    board: "wbbpe",
    id: "2",
    roman: "II",
    label: "Class 2",
    blurb:
      "WBBPE Class 2 — Bengali medium (বাংলা মাধ্যম), from the integrated book ‘আমার বই’ (Amar Boi): Bangla, English & Ganit.",
    subjects: [
      {
        key: "bengali",
        name: "বাংলা",
        icon: "📖",
        color: "#7b54d3",
        chapters: [
          { order: 1, title: "যুক্তবর্ণ ও তার ব্যবহার", slug: "conjuncts" },
          { order: 2, title: "শব্দার্থ", slug: "word-meanings" },
          { order: 3, title: "বিপরীত শব্দ", slug: "opposite-words" },
          { order: 4, title: "এক ও একাধিক (বচন)", slug: "singular-plural" },
          { order: 5, title: "নাম-শব্দ চেনা", slug: "naming-words" },
          { order: 6, title: "বাক্য গঠন", slug: "making-sentences" },
          { order: 7, title: "যতিচিহ্ন", slug: "punctuation" },
          { order: 8, title: "গল্প পড়ে বুঝি", slug: "reading-comprehension" },
        ],
      },
      {
        key: "english",
        name: "ইংরেজি",
        icon: "✏️",
        color: "#1faf6b",
        chapters: [
          { order: 1, title: "Naming Words", slug: "naming-words" },
          { order: 2, title: "A, An and The", slug: "a-an-the" },
          { order: 3, title: "This and That", slug: "this-and-that" },
          { order: 4, title: "One and Many", slug: "singular-and-plural" },
          { order: 5, title: "Action Words", slug: "action-words" },
          { order: 6, title: "Making Sentences", slug: "making-sentences" },
          { order: 7, title: "Months of the Year", slug: "months-of-the-year" },
          { order: 8, title: "Reading a Short Passage", slug: "reading-comprehension" },
        ],
      },
      {
        key: "maths",
        name: "গণিত",
        icon: "➗",
        color: "#ff5d73",
        chapters: [
          { order: 1, title: "সংখ্যা: ১ থেকে ১০০", slug: "numbers-to-100" },
          { order: 2, title: "শতক, দশক ও একক", slug: "place-value" },
          { order: 3, title: "সংখ্যার তুলনা ও ক্রম", slug: "compare-and-order" },
          { order: 4, title: "যোগ (হাতে রেখে)", slug: "addition" },
          { order: 5, title: "বিয়োগ (ধার করে)", slug: "subtraction" },
          { order: 6, title: "গুণের ধারণা", slug: "multiplication-intro" },
          { order: 7, title: "নামতা", slug: "multiplication-tables" },
          { order: 8, title: "ভাগের ধারণা", slug: "division-intro" },
          { order: 9, title: "পরিমাপ: দৈর্ঘ্য ও ওজন", slug: "measurement" },
          { order: 10, title: "টাকা-পয়সা", slug: "money" },
          { order: 11, title: "সময় ও দিনপঞ্জি", slug: "time-and-calendar" },
        ],
      },
    ],
  },
  {
    board: "wbbpe",
    id: "3",
    roman: "III",
    label: "Class 3",
    blurb:
      "WBBPE Class 3 — Bengali medium (বাংলা মাধ্যম). বাংলা skills from পাতাবাহার, with English, Ganit and পরিবেশ (EVS) to follow.",
    subjects: [
      {
        key: "bengali",
        name: "বাংলা",
        icon: "📖",
        color: "#7b54d3",
        chapters: [
          { order: 1, title: "সমার্থক শব্দ", slug: "synonyms" },
          { order: 2, title: "বিপরীত শব্দ", slug: "antonyms" },
          { order: 3, title: "শব্দার্থ ও বানান", slug: "word-meanings-spelling" },
          { order: 4, title: "লিঙ্গ", slug: "gender" },
          { order: 5, title: "নাম, কাজ ও গুণ-শব্দ", slug: "word-types" },
          { order: 6, title: "কর্তা, কর্ম ও ক্রিয়া", slug: "sentence-parts" },
          { order: 7, title: "বাক্য রচনা", slug: "making-sentences" },
          { order: 8, title: "পড়ে বুঝি", slug: "reading-comprehension" },
        ],
      },
      {
        key: "english",
        name: "ইংরেজি",
        icon: "✏️",
        color: "#1faf6b",
        chapters: [
          { order: 1, title: "Describing Words", slug: "describing-words" },
          { order: 2, title: "Pronouns", slug: "pronouns" },
          { order: 3, title: "Am, Is, Are", slug: "am-is-are" },
          { order: 4, title: "Has and Have", slug: "has-and-have" },
          { order: 5, title: "Opposite Words", slug: "opposite-words" },
          { order: 6, title: "Days of the Week", slug: "days-of-the-week" },
          { order: 7, title: "Making Sentences", slug: "making-sentences" },
          { order: 8, title: "Reading a Passage", slug: "reading-comprehension" },
        ],
      },
      {
        key: "maths",
        name: "গণিত",
        icon: "➗",
        color: "#ff5d73",
        chapters: [
          { order: 1, title: "সংখ্যা: ১ থেকে ১০০০", slug: "numbers-to-1000" },
          { order: 2, title: "স্থানীয় মান: হাজার", slug: "place-value" },
          { order: 3, title: "সংখ্যার তুলনা ও ক্রম", slug: "compare-and-order" },
          { order: 4, title: "যোগ", slug: "addition" },
          { order: 5, title: "বিয়োগ", slug: "subtraction" },
          { order: 6, title: "গুণ", slug: "multiplication" },
          { order: 7, title: "ভাগ", slug: "division" },
          { order: 8, title: "ভগ্নাংশ: অর্ধেক ও সিকি", slug: "fractions" },
          { order: 9, title: "পরিমাপ", slug: "measurement" },
          { order: 10, title: "টাকা-পয়সা", slug: "money" },
          { order: 11, title: "সময় ও দিনপঞ্জি", slug: "time-and-calendar" },
        ],
      },
      {
        key: "evs",
        name: "পরিবেশ",
        icon: "🌿",
        color: "#1faf6b",
        chapters: [
          { order: 1, title: "আমাদের শরীর", slug: "our-body" },
          { order: 2, title: "আমাদের খাদ্য", slug: "our-food" },
          { order: 3, title: "আমাদের পোশাক", slug: "our-clothing" },
          { order: 4, title: "আমাদের ঘরবাড়ি", slug: "our-home" },
          { order: 5, title: "আমাদের পরিবার", slug: "our-family" },
          { order: 6, title: "গাছপালা", slug: "plants" },
          { order: 7, title: "পশুপাখি", slug: "animals" },
          { order: 8, title: "জল ও বাতাস", slug: "water-and-air" },
          { order: 9, title: "পরিচ্ছন্নতা ও সুস্থতা", slug: "health-and-cleanliness" },
        ],
      },
    ],
  },
  {
    board: "wbbpe",
    id: "4",
    roman: "IV",
    label: "Class 4",
    blurb:
      "WBBPE Class 4 — Bengali medium (বাংলা মাধ্যম). বাংলা skills from পাতাবাহার, with English, Ganit and পরিবেশ (EVS) to follow.",
    subjects: [
      {
        key: "bengali",
        name: "বাংলা",
        icon: "📖",
        color: "#7b54d3",
        chapters: [
          { order: 1, title: "সবার আমি ছাত্র", slug: "shobar-ami-chhatro" },
          { order: 2, title: "নরহরি দাস", slug: "narahari-das" },
          { order: 3, title: "কোথাও আমার", slug: "kothao-amar" },
          { order: 4, title: "তোত্তো-চানের অ্যাডভেঞ্চার", slug: "totto-chan" },
          { order: 5, title: "বনভোজন", slug: "bonbhojon" },
          { order: 6, title: "ছেলেবেলার দিনগুলি", slug: "chelebelar-dinguli" },
          { order: 7, title: "মালগাড়ি", slug: "malgari" },
          { order: 8, title: "বনের খবর", slug: "boner-khobor" },
          { order: 9, title: "বিচিত্র সাধ", slug: "bichitra-sadh" },
          { order: 10, title: "আমাজনের জঙ্গলে", slug: "amazoner-jongole" },
          { order: 11, title: "আমি সাগর পাড়ি দেবো", slug: "ami-sagar-pari-debo" },
          { order: 12, title: "দক্ষিণমেরু অভিযান", slug: "dokkhinmeru-obhijan" },
          { order: 50, title: "বিশেষ্য ও সর্বনাম", slug: "noun-pronoun" },
          { order: 51, title: "বিশেষণ ও ক্রিয়া", slug: "adjective-verb" },
          { order: 52, title: "লিঙ্গ ও বচন", slug: "gender-number" },
          { order: 53, title: "সমার্থক ও বিপরীত শব্দ", slug: "synonyms-antonyms" },
          { order: 54, title: "বাগধারা", slug: "idioms" },
          { order: 55, title: "যুক্তবর্ণ ও বানান", slug: "conjuncts-spelling" },
          { order: 56, title: "বাক্যের প্রকার", slug: "sentence-types" },
          { order: 57, title: "পড়ে বুঝি", slug: "reading-comprehension" },
        ],
      },
      {
        key: "english",
        name: "ইংরেজি",
        icon: "✏️",
        color: "#1faf6b",
        chapters: [
          { order: 1, title: "Common & Proper Nouns", slug: "nouns" },
          { order: 2, title: "Possessive Pronouns", slug: "possessives" },
          { order: 3, title: "Adjectives", slug: "adjectives" },
          { order: 4, title: "Verbs: Present Continuous", slug: "verbs-tense" },
          { order: 5, title: "Adverbs", slug: "adverbs" },
          { order: 6, title: "Prepositions", slug: "prepositions" },
          { order: 7, title: "Was and Were", slug: "was-were" },
          { order: 8, title: "Reading a Passage", slug: "reading-comprehension" },
        ],
      },
      {
        key: "maths",
        name: "গণিত",
        icon: "➗",
        color: "#ff5d73",
        chapters: [
          { order: 1, title: "বড়ো সংখ্যা", slug: "large-numbers" },
          { order: 2, title: "স্থানীয় মান: দশ হাজার", slug: "place-value" },
          { order: 3, title: "যোগ ও বিয়োগ", slug: "addition-subtraction" },
          { order: 4, title: "গুণ", slug: "multiplication" },
          { order: 5, title: "ভাগ", slug: "division" },
          { order: 6, title: "গুণিতক ও উৎপাদক", slug: "multiples-factors" },
          { order: 7, title: "ভগ্নাংশ", slug: "fractions" },
          { order: 8, title: "পরিমাপ", slug: "measurement" },
          { order: 9, title: "টাকা-পয়সা", slug: "money" },
          { order: 10, title: "সময় ও দিনপঞ্জি", slug: "time-and-calendar" },
          { order: 11, title: "জ্যামিতি", slug: "geometry" },
        ],
      },
      {
        key: "evs",
        name: "পরিবেশ",
        icon: "🌿",
        color: "#1faf6b",
        chapters: [
          { order: 1, title: "জীবজগৎ ও জড়জগৎ", slug: "living-and-nonliving" },
          { order: 2, title: "প্রাণীদের বৈচিত্র্য", slug: "animal-variety" },
          { order: 3, title: "গাছপালার বৈচিত্র্য", slug: "plant-variety" },
          { order: 4, title: "জড়বস্তুর ধর্ম", slug: "matter" },
          { order: 5, title: "আমাদের দাঁত ও হজম", slug: "teeth-and-digestion" },
          { order: 6, title: "শ্বাসকার্য", slug: "breathing" },
          { order: 7, title: "আবহাওয়া", slug: "weather" },
          { order: 8, title: "আমাদের আকাশ", slug: "sky" },
          { order: 9, title: "সম্পদ ও জীবিকা", slug: "resources-and-livelihood" },
        ],
      },
    ],
  },
  {
    board: "wbbpe",
    id: "5",
    roman: "V",
    label: "Class 5",
    blurb:
      "WBBPE Class 5 — Bengali medium (বাংলা মাধ্যম). বাংলা skills from পাতাবাহার, with English, Ganit and পরিবেশ (EVS) to follow.",
    subjects: [
      {
        key: "bengali",
        name: "বাংলা",
        icon: "📖",
        color: "#7b54d3",
        chapters: [
          { order: 1, title: "পদ পরিচয় ও অব্যয়", slug: "parts-of-speech" },
          { order: 2, title: "ক্রিয়ার কাল", slug: "verb-tense" },
          { order: 3, title: "সন্ধি", slug: "sandhi" },
          { order: 4, title: "উপসর্গ ও প্রত্যয়", slug: "prefix-suffix" },
          { order: 5, title: "বিরামচিহ্ন", slug: "punctuation" },
          { order: 6, title: "উদ্দেশ্য ও বিধেয়", slug: "subject-predicate" },
          { order: 7, title: "প্রবাদ-প্রবচন", slug: "proverbs" },
          { order: 8, title: "পড়ে বুঝি", slug: "reading-comprehension" },
        ],
      },
      {
        key: "english",
        name: "ইংরেজি",
        icon: "✏️",
        color: "#1faf6b",
        chapters: [
          { order: 1, title: "Subject & Predicate", slug: "subject-predicate" },
          { order: 2, title: "Kinds of Nouns", slug: "nouns" },
          { order: 3, title: "Subject & Object Pronouns", slug: "pronouns" },
          { order: 4, title: "Simple Past Tense", slug: "past-tense" },
          { order: 5, title: "Simple Future Tense", slug: "future-tense" },
          { order: 6, title: "Articles: a, an, the", slug: "articles" },
          { order: 7, title: "Conjunctions", slug: "conjunctions" },
          { order: 8, title: "Reading a Passage", slug: "reading-comprehension" },
        ],
      },
      {
        key: "maths",
        name: "গণিত",
        icon: "➗",
        color: "#ff5d73",
        chapters: [
          { order: 1, title: "বড়ো সংখ্যা ও স্থানীয় মান", slug: "large-numbers" },
          { order: 2, title: "যোগ ও বিয়োগ", slug: "addition-subtraction" },
          { order: 3, title: "গুণ", slug: "multiplication" },
          { order: 4, title: "ভাগ", slug: "division" },
          { order: 5, title: "গুণিতক ও উৎপাদক", slug: "multiples-factors" },
          { order: 6, title: "ভগ্নাংশ", slug: "fractions" },
          { order: 7, title: "দশমিক", slug: "decimals" },
          { order: 8, title: "পরিমাপ", slug: "measurement" },
          { order: 9, title: "পরিসীমা ও ক্ষেত্রফল", slug: "perimeter-area" },
          { order: 10, title: "জ্যামিতি", slug: "geometry" },
          { order: 11, title: "টাকা-পয়সা", slug: "money" },
        ],
      },
      { key: "evs", name: "পরিবেশ", icon: "🌿", color: "#1faf6b", chapters: [
          { order: 1, title: "কঙ্কাল ও সন্ধি", slug: "skeleton" },
          { order: 2, title: "সুস্থ থাকা ও রোগ", slug: "health-and-disease" },
          { order: 3, title: "মাটি", slug: "soil" },
          { order: 4, title: "জল ও জলাভূমি", slug: "water-and-wetlands" },
          { order: 5, title: "জীববৈচিত্র্য", slug: "biodiversity" },
          { order: 6, title: "পরিবেশ দূষণ ও সংরক্ষণ", slug: "pollution-conservation" },
          { order: 7, title: "আমাদের রাজ্য পশ্চিমবঙ্গ", slug: "our-state" },
          { order: 8, title: "কৃষি ও মৎস্য", slug: "agriculture-fishery" },
          { order: 9, title: "বনভূমি ও বন্যপ্রাণী", slug: "forests-wildlife" },
        ] },
    ],
  },
];

/** Every class across every board. */
export const ALL_CLASSES: ClassDef[] = [...CBSE_CLASSES, ...WBBPE_CLASSES];

/** Back-compat alias: existing CBSE-only views import `CLASSES`. */
export const CLASSES: ClassDef[] = CBSE_CLASSES;
