import type { ClassDef, ChapterStub } from "@/lib/types";

/** Stable slug from a human title (matches authored chapter slugs). */
export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Build a chapter roadmap from [order, title] pairs. */
function chapters(list: [number, string][]): ChapterStub[] {
  return list.map(([order, title]) => ({ order, title, slug: slugify(title) }));
}

const ICON = {
  maths: "➗",
  science: "⚛️",
  social: "🏛️",
  english: "✏️",
} as const;

const COLOR = {
  maths: "#ff5d73",
  science: "#3257f0",
  social: "#b56a16",
  english: "#1faf6b",
} as const;

export const CLASSES: ClassDef[] = [
  {
    id: "6",
    roman: "VI",
    label: "Class 6",
    blurb: "Class 6 CBSE — new NCERT Ganita Prakash (Maths) & Curiosity (Science).",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "Patterns in Mathematics"],
          [2, "Lines and Angles"],
          [3, "Number Play"],
          [4, "Data Handling and Presentation"],
          [5, "Prime Time"],
          [6, "Perimeter and Area"],
          [7, "Fractions"],
          [8, "Playing with Constructions"],
          [9, "Symmetry"],
          [10, "The Other Side of Zero"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "The Wonderful World of Science"],
          [2, "Diversity in the Living World"],
          [3, "Mindful Eating A Path to a Healthy Body"],
          [4, "Exploring Magnets"],
          [5, "Measurement of Length and Motion"],
          [6, "Materials Around Us"],
          [7, "Temperature and its Measurement"],
          [8, "A Journey through States of Water"],
          [9, "Methods of Separation in Everyday Life"],
          [10, "Living Creatures Exploring their Characteristics"],
          [11, "Natures Treasures"],
          [12, "Beyond Earth"],
        ]),
      },
    ],
  },
  {
    id: "7",
    roman: "VII",
    label: "Class 7",
    blurb: "Class 7 CBSE — new NCERT Ganita Prakash (Maths) & Curiosity (Science).",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "Large Numbers Around Us"],
          [2, "Arithmetic Expressions"],
          [3, "A Peek Beyond the Point"],
          [4, "Expressions using Letter-Numbers"],
          [5, "Parallel and Intersecting Lines"],
          [6, "Number Play"],
          [7, "A Tale of Three Intersecting Lines"],
          [8, "Working with Fractions"],
          [9, "Geometric Twins"],
          [10, "Operations with Integers"],
          [11, "Finding Common Ground"],
          [12, "Another Peek Beyond the Point"],
          [13, "Connecting the Dots"],
          [14, "Constructions and Tilings"],
          [15, "Finding the Unknown"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "The Ever-Evolving World of Science"],
          [2, "Exploring Substances Acidic Basic and Neutral"],
          [3, "Electricity Circuits and their Components"],
          [4, "The World of Metals and Non-metals"],
          [5, "Changes Around Us Physical and Chemical"],
          [6, "Adolescence A Stage of Growth and Change"],
          [7, "Heat Transfer in Nature"],
          [8, "Measurement of Time and Motion"],
          [9, "Life Processes in Animals"],
          [10, "Life Processes in Plants"],
          [11, "Light Shadows and Reflections"],
          [12, "Earth Moon and the Sun"],
        ]),
      },
    ],
  },
  {
    id: "8",
    roman: "VIII",
    label: "Class 8",
    blurb: "Class 8 CBSE — new NCERT Ganita Prakash (Maths) & Curiosity (Science).",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "A Square and A Cube"],
          [2, "Power Play"],
          [3, "A Story of Numbers"],
          [4, "Quadrilaterals"],
          [5, "Number Play"],
          [6, "We Distribute Yet Things Multiply"],
          [7, "Proportional Reasoning 1"],
          [8, "Fractions in Disguise"],
          [9, "The Baudhayana Pythagoras Theorem"],
          [10, "Proportional Reasoning 2"],
          [11, "Exploring Some Geometric Themes"],
          [12, "Tales by Dots and Lines"],
          [13, "Algebra Play"],
          [14, "Area"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "Exploring the Investigative World of Science"],
          [2, "The Invisible Living World Beyond Our Naked Eye"],
          [3, "Health The Ultimate Treasure"],
          [4, "Electricity Magnetic and Heating Effects"],
          [5, "Exploring Forces"],
          [6, "Pressure Winds Storms and Cyclones"],
          [7, "Particulate Nature of Matter"],
          [8, "Nature of Matter Elements Compounds and Mixtures"],
          [9, "The Amazing World of Solutes Solvents and Solutions"],
          [10, "Light Mirrors and Lenses"],
          [11, "Keeping Time with the Skies"],
          [12, "How Nature Works in Harmony"],
          [13, "Our Home Earth A Unique Life Sustaining Planet"],
        ]),
      },
    ],
  },
  {
    id: "9",
    roman: "IX",
    label: "Class 9",
    blurb: "Class 9 CBSE — Maths, Science, Social Science and English.",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "Number Systems"],
          [2, "Polynomials"],
          [3, "Coordinate Geometry"],
          [4, "Linear Equations in Two Variables"],
          [5, "Introduction to Euclids Geometry"],
          [6, "Lines and Angles"],
          [7, "Triangles"],
          [8, "Quadrilaterals"],
          [9, "Circles"],
          [10, "Herons Formula"],
          [11, "Surface Areas and Volumes"],
          [12, "Statistics"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "Matter in Our Surroundings"],
          [2, "Is Matter Around Us Pure"],
          [3, "Atoms and Molecules"],
          [4, "Structure of the Atom"],
          [5, "The Fundamental Unit of Life"],
          [6, "Tissues"],
          [7, "Motion"],
          [8, "Force and Laws of Motion"],
          [9, "Gravitation"],
          [10, "Work and Energy"],
          [11, "Sound"],
          [12, "Improvement in Food Resources"],
        ]),
      },
      {
        key: "social-science",
        name: "Social Science",
        icon: ICON.social,
        color: COLOR.social,
        chapters: chapters([
          [1, "The French Revolution"],
          [2, "Socialism in Europe and the Russian Revolution"],
          [3, "Nazism and the Rise of Hitler"],
          [4, "Forest Society and Colonialism"],
          [5, "Pastoralists in the Modern World"],
          [6, "India Size and Location"],
          [7, "Physical Features of India"],
          [8, "Drainage"],
          [9, "Climate"],
          [10, "Natural Vegetation and Wildlife"],
          [11, "Population"],
          [12, "What is Democracy Why Democracy"],
          [13, "Constitutional Design"],
          [14, "Electoral Politics"],
          [15, "Working of Institutions"],
          [16, "Democratic Rights"],
          [17, "The Story of Village Palampur"],
          [18, "People as Resource"],
          [19, "Poverty as a Challenge"],
          [20, "Food Security in India"],
        ]),
      },
      {
        key: "english",
        name: "English",
        icon: ICON.english,
        color: COLOR.english,
        chapters: chapters([
          [1, "The Fun They Had"],
          [2, "The Sound of Music"],
          [3, "The Little Girl"],
          [4, "A Truly Beautiful Mind"],
          [5, "The Snake and the Mirror"],
          [6, "My Childhood"],
          [7, "Reach for the Top"],
          [8, "Kathmandu"],
          [9, "If I Were You"],
          [10, "The Road Not Taken"],
          [11, "Wind"],
          [12, "Rain on the Roof"],
          [13, "The Lake Isle of Innisfree"],
          [14, "A Legend of the Northland"],
          [15, "No Men Are Foreign"],
          [16, "On Killing a Tree"],
          [17, "A Slumber Did My Spirit Seal"],
          [18, "The Lost Child"],
          [19, "The Adventures of Toto"],
          [20, "Iswaran the Storyteller"],
          [21, "In the Kingdom of Fools"],
          [22, "The Happy Prince"],
          [23, "Weathering the Storm in Ersama"],
          [24, "The Last Leaf"],
          [25, "A House Is Not a Home"],
          [26, "The Beggar"],
          [27, "Grammar and Writing Skills"],
        ]),
      },
    ],
  },
  {
    id: "10",
    roman: "X",
    label: "Class 10",
    blurb:
      "Class 10 CBSE board prep — chapter notes, formulas, MCQ quizzes and important questions.",
    subjects: [
      {
        key: "maths",
        name: "Maths",
        icon: ICON.maths,
        color: COLOR.maths,
        chapters: chapters([
          [1, "Real Numbers"],
          [2, "Polynomials"],
          [3, "Pair of Linear Equations in Two Variables"],
          [4, "Quadratic Equations"],
          [5, "Arithmetic Progressions"],
          [6, "Triangles"],
          [7, "Coordinate Geometry"],
          [8, "Introduction to Trigonometry"],
          [9, "Some Applications of Trigonometry"],
          [10, "Circles"],
          [11, "Areas Related to Circles"],
          [12, "Surface Areas and Volumes"],
          [13, "Statistics"],
          [14, "Probability"],
        ]),
      },
      {
        key: "science",
        name: "Science",
        icon: ICON.science,
        color: COLOR.science,
        chapters: chapters([
          [1, "Chemical Reactions and Equations"],
          [2, "Acids Bases and Salts"],
          [3, "Metals and Non-metals"],
          [4, "Carbon and its Compounds"],
          [5, "Life Processes"],
          [6, "Control and Coordination"],
          [7, "How do Organisms Reproduce"],
          [8, "Heredity"],
          [9, "Light Reflection and Refraction"],
          [10, "The Human Eye and the Colourful World"],
          [11, "Electricity"],
          [12, "Magnetic Effects of Electric Current"],
          [13, "Our Environment"],
        ]),
      },
      {
        key: "social-science",
        name: "Social Science",
        icon: ICON.social,
        color: COLOR.social,
        chapters: chapters([
          [1, "The Rise of Nationalism in Europe"],
          [2, "Nationalism in India"],
          [3, "The Making of a Global World"],
          [4, "The Age of Industrialisation"],
          [5, "Print Culture and the Modern World"],
          [6, "Resources and Development"],
          [7, "Forest and Wildlife Resources"],
          [8, "Water Resources"],
          [9, "Agriculture"],
          [10, "Minerals and Energy Resources"],
          [11, "Manufacturing Industries"],
          [12, "Lifelines of National Economy"],
          [13, "Power Sharing"],
          [14, "Federalism"],
          [15, "Gender Religion and Caste"],
          [16, "Political Parties"],
          [17, "Outcomes of Democracy"],
          [18, "Development"],
          [19, "Sectors of the Indian Economy"],
          [20, "Money and Credit"],
          [21, "Globalisation and the Indian Economy"],
          [22, "Consumer Rights"],
        ]),
      },
      {
        key: "english",
        name: "English",
        icon: ICON.english,
        color: COLOR.english,
        chapters: chapters([
          [1, "A Letter to God"],
          [2, "Nelson Mandela A Long Walk to Freedom"],
          [3, "Two Stories about Flying"],
          [4, "From the Diary of Anne Frank"],
          [5, "Glimpses of India"],
          [6, "Mijbil the Otter"],
          [7, "Madam Rides the Bus"],
          [8, "The Sermon at Benares"],
          [9, "The Proposal"],
          [10, "Dust of Snow"],
          [11, "Fire and Ice"],
          [12, "A Tiger in the Zoo"],
          [13, "How to Tell Wild Animals"],
          [14, "The Ball Poem"],
          [15, "Amanda"],
          [16, "The Trees"],
          [17, "Fog"],
          [18, "The Tale of Custard the Dragon"],
          [19, "For Anne Gregory"],
          [20, "A Triumph of Surgery"],
          [21, "The Thiefs Story"],
          [22, "The Midnight Visitor"],
          [23, "A Question of Trust"],
          [24, "Footprints without Feet"],
          [25, "The Making of a Scientist"],
          [26, "The Necklace"],
          [27, "Bholi"],
          [28, "The Book That Saved the Earth"],
          [29, "Grammar and Writing Skills"],
        ]),
      },
    ],
  },
];
